const Types = {
    LOGIN: 'LOGIN',
    AUTH_FAILED: 'AUTH_FAILED',
    REGISTER: "REGISTER",
    REGISTER_FAILED: 'REGISTER_FAILED',
    FORGET_PASS_SUCCEESS: 'FORGET_PASS_SUCCEESS',
    FORGET_PASS_FAILED: 'FORGET_PASS_FAILED'

  }


export default Types;