const Types = {
    LOGIN: 'LOGIN',
    AUTH_FAILED: 'AUTH_FAILED',
    REGISTER: "REGISTER",
    REGISTER_FAILED: 'REGISTER_FAILED',
    FORGET_PASS_SUCCEESS: 'FORGET_PASS_SUCCEESS',
    FORGET_PASS_FAILED: 'FORGET_PASS_FAILED',
    VERIFY_SUCCESS : 'VERIFY_SUCCESS',
    VERIFY_FAILED : 'VERIFY_FAILED',
    RESET_SUCCESS : 'RESET_SUCCESS',
    RESET_FAILED : 'RESET_FAILED',
    USERS_LIST : 'USERS_LIST',
    LIST_ERROR : 'LIST_ERROR',
  }


export default Types;